---

- name: Add the Kevin Kelley emacs26 repository
  apt_repository:
    repo: ppa:kelleyk/emacs
  become: yes

- name: install emacs 26
  apt:
    name: emacs26
  become: yes

- name: install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d
  become: yes
  become_user: "{{ local_username }}"

- name: download reveal.js for org mode presentations
  unarchive:
    src: "https://github.com/hakimel/reveal.js/archive/3.7.0.zip"
    dest: ~/code
    remote_src: yes
  become: yes
  become_user: "{{ local_username }}"
