---

- name: pull dotfiles from github
  git:
    repo: ssh://git@github.com/CGDS/.dotdot
    dest: ~/.dotdot

- name: "link {{ item }}"
  file:
    src: "~/.dotdot/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items: "{{ dotfiles_to_symlink }}"

