---

- name: pull dotfiles from github
  git:
    repo: https://github.com/CGDS/laptop.git
    dest: ~/.dotdot
  become: yes
  become_user: "{{ local_username }}"

- name: "symlink dotfiles"
  file:
    src: "~/.dotdot/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items: "{{ dotfiles_to_symlink }}"
  become: yes
  become_user: "{{ local_username }}"

