---

- name: Install java 8 open sdk
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes
  become: yes

- name: Install leiningen, clojure
  apt:
    name: leiningen
    state: present
    update_cache: yes
  become: yes
