---

- name: install zsh
  apt:
    name: zsh
    state: latest
  become: yes
  become_user: root
  register: installation

- name: change user's shell to zsh
  become: yes
  become_user: root
  command: chsh -s /bin/zsh "{{ local_username }}"

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  register: cloning
  become: yes
  become_user: "{{ local_username }}"

