---

- name: install zsh
  apt:
    name: zsh
    state: latest
  become: yes
  register: installation

- name: change user's shell to zsh
  user:
    name: "{{ local_username }}"
    shell: /bin/zsh
  become: yes
  become_user: root
  when: installation is succeeded

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  register: cloning

