---
- name: make base code dir
  file:
    path: "/home/{{ local_username }}/code"
    state: directory
    owner: "{{ local_username }}"

- name: pull org repo
  git:
    repo: https://github.com/CGDS/org
    dest: ~/code/org
  become: yes
  become_user: "{{ local_username }}"
