---

- name: install pg_ctlcluster & other scripts
  apt:
    name: postgresql-common
  become: yes

- name: install postgres 10
  apt:
    name: "{{ item }}"
  become: yes
  with_items: "{{ postgres_packages }}"
