---

- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git 
    dest: ~/.rbenv

- name: install ruby-build as rbenv plugin
  git:
    repo: https://github.com/rbenv/ruby-build.git 
    dest: ~/.rbenv/plugins/ruby-build

- name: install ruby versions & rehash rbenv
  shell: "rbenv install {{ item }} -s && rbenv rehash"
  with_items: "{{ ruby_versions }}"

# Install default gems without rbenv-default-gems so gems can be updated independently of ruby versions
- name: install default gems
  shell: "~/.rbenv/versions/{{ item[0] }}/bin/gem install {{item[1]}}"
  with_nested:
    - "{{ ruby_versions }}"
    - "{{ default_gems }}"

- name: set global ruby version to latest install
  shell: "rbenv global {{ ruby_versions[0] }}"
