---

- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git 
    dest: ~/.rbenv

- name: install ruby-build as rbenv plugin
  git:
    repo: https://github.com/rbenv/ruby-build.git 
    dest: ~/.rbenv/plugins/ruby-build

- name: install rbenv-default-gems as plugin
  git:
    repo: https://github.com/rbenv/rbenv-default-gems.git
    dest: ~/.rbenv/plugins/rbenv-default-gems

- name: add default gems
  copy:
    dest: ~/.rbenv/default-gems
    content: |
      bundler
      rails
      rspec
      pry

- name: install ruby versions
  shell: "rbenv install {{ item }} -s && rbenv rehash"
  with_items: "{{ ruby_versions }}"
